site_name: Wirecard - AcceptSDK Partner Documentation

#- MDS-VOD:
#    - 'An Overview of Video on Demand': 'temp.md'

theme: 'material'
#theme_dir: 'mkdocs-material/material'

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

#extra_css:
#  - 'stylesheets/acceptsdk.css'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/squidfunk'
    - type: 'twitter'
      link: 'https://twitter.com/squidfunk'
    - type: 'linkedin'
      link: 'https://de.linkedin.com/in/martin-donath-20a95039'
  palette:
    primary: 'indigo'
    accent: 'red'
#  logo: 'images/logo.png'

# Page tree
pages:
  - Welcome!: index.md
  - Getting Started:
    - The Architecture:
      - The mPOS Architecture: mpos-architecture.md
      - The SDK Architecture: sdk-architecture.md
    - Your Test Environment:
      - Set up Terminals: setup-terminals.md
      - Set up Public Test: setup-publictest.md

  - Integrating the SDK:
    - Getting Started:
      - Set up the SDKs: int-setup.md
      - Initialization: int-initialization.md
    - Sale Transactions:
      - Sale Overview: int-sale-overview.md
      - Payment: int-payment.md
      - Sale Request: int-salerequest.md
      - Terminal Discovery: int-terminaldiscovery.md
      - Sale Returns: int-salereturns.md
      - Sales History: int-saleshistory.md
      - Sales Statistics: int-salesstatistics.md
    - Cash Management:
      - Overview of Cash Management: cash-overview.md
      - Cash Register: cash-register.md
      - Shifts: cash-shifts.md
      - Pay In/Out: cash-payinout.md
      - Shift Activity: cash-shiftactivity.md
      - Shift Report: cash-shiftreport.md
      - Cashiers: cash-cashiers.md
    - Product Catalogue:
      - Overview of Product Catalogue: overview-productcatalogue.md
      - Product Catalogue Maintenance: productcatalogue-maintenance.md
      - Product Changes: productchanges.md
      - Product Stocks (ERP): productstocks-erp.md
      - Product Prices (ERP): productprices-erp.md
    - Support:
      - Terminal Update: support-terminalupdate.md
      - User Management: support-usermanagement.md
      - Customer Management: support-customermanagement.md
      - Receipt Printing: support-receiptprinting.md
      - Barcode Scanning: support-barcodescanning.md

  - iOS SDK Reference:
    - Class Library:
      - AcceptBackendException: temp-test.md
      - AcceptCashDrawerExtension: temp.md
    - Package Library:
      - de.wirecard.acceptsdk2: temp.md
      - de.wirecard.acceptsdk2.core.model.sale: temp.md

  - Android SDK Reference:
    - Class Library:
      - AcceptBackendException: temp-test.md
      - AcceptSDK: temp.md
      - AcceptSdkBuilder: temp.md
      - AcceptSdkFactory: temp.md
    - Package Library:
      - de.wirecard.acceptsdk2: temp.md
      - de.wirecard.acceptsdk2.core.model.sale: temp.md

  - Switch Back-end Reference: switch-reference.md

  - Glossary: glossary-terminology.md
  
  - Appendices:
    - A - Other: appa-other.md
    - B - EMV Transaction Flow: appb-emv.md
#    - C - Guide to Payment Processing (Both Platforms): appc-payment.md
